name: Deploy API

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: Deploy API to Cloudflare Workers
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: api
      - run: npm install
