name: Scrape Kings League Website Abraham

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: '0 */5 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: |
          node scraping/leaderboard.js
          git config user.name kings-league-bot-abraham
          git add -A
          git commit -m "[bot] update kings league Database"
          git push origin master
